Student.create(name: "Stella Langat", email: "stella@gmail.com")
Student.create(name: "Candy Joy", email: "candy@gmail.com")
Student.create(name: "Emilly Joy", email: "emilyjoy@gmail.com")
Student.create(name: "Panda Kite", email: "panda@gmail.com")
Student.create(name: "John Doe", email: "john@gmail.com")
