# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 3.0"
gem "sinatra-activerecord", "~> 2.0"
gem "activerecord", "~> 7.0"
gem "rake", "~> 13.0"
gem "sqlite3", "~> 1.6"
gem "require_all", "~> 3.0"
gem "pry", "~> 0.14.2"

gem "rack-contrib", "~> 2.3"
gem "rerun", "~> 0.14.0"
gem "puma", "~> 6.3"

gem "rack-cors", "~> 2.0"
